# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebsite', '0002_auto_20170730_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchantPhoneNum',
            field=models.BigIntegerField(unique=True),
        ),
    ]
