# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebsite', '0003_auto_20170730_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealprovider',
            name='dealProEmail',
            field=models.EmailField(default='abc@abc.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealprovider',
            name='dealProLocLat',
            field=models.SmallIntegerField(default=1,),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealprovider',
            name='dealProLocLong',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealprovider',
            name='dealProPhoneNum',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='dealDuration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='dealImg',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='dealStartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
