# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWebsite', '0004_auto_20170730_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='dealStartTime',
        ),
        migrations.AlterField(
            model_name='deals',
            name='dealImg',
            field=models.CharField(max_length=1000),
        ),
    ]
